export {default as Img1} from "./Group 1103.png"
export {default as Img2} from "./Rectangle 102.png"
export {default as Img3} from "./Rectangle 103.png"
export {default as Img4} from "./Rectangle 104.png"
export {default as Img5} from "./Rectangle 105.png"
export {default as Img6} from "./Rectangle 106.png"
export {default as Img7} from "./Rectangle 107.png"